### ISSUE TITLE
Adding to .gitignore

### ISSUE THREAD

**Issue by tbrown2** [louiehernandez95/Twitter#1]
You might want to edit your gitignore to include more files from your Eclipse project . here is a useful [link you can use](https://github.com/github/gitignore/blob/master/Global/Eclipse.gitignore).

**Comment by Rhernandez513** [comment]
@louiehernandez95 @tbrown2 

I recommend

https://www.gitignore.io/

it even has a command line interface if thats your thing :+1:

**Comment by louiehernandez95** [comment]
Thanks for the feedback you guys I will make sure to check out both sources!
